# Generated by Django 3.2.13 on 2022-06-29 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['created_at']},
        ),
    ]
