# Generated by Django 3.2.13 on 2022-06-30 03:28

import apps.wallets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20220629_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='alias',
            field=models.CharField(default=apps.wallets.models.create_hash, max_length=25),
        ),
    ]
